### ISSUE TITLE
One DID method to rule them all

### ISSUE THREAD

**Issue by travisleithead** [w3c/did-wg-charter#13]
This is part of the feedback from Microsoft's ballot response to the DID Core spec transition to REC AC review. As it pertains to future work on that spec, @iherman encouraged me to file it here for consideration in the charter process (as applicable). See also #11, #12

Microsoft would like the Working Group to take the challenge of defining a new fully interoperable DID method that meets industry use cases and can be specified as a mandatory to implement reference method.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-08-31-did#section6) on 2021-08-31

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

### 6. Next DID WG Charter 

_See github issue [did-wg-charter#11](https://github.com/w3c/did-wg-charter/issues/11), [did-wg-charter#12](https://github.com/w3c/did-wg-charter/issues/12), [did-wg-charter#13](https://github.com/w3c/did-wg-charter/issues/13)._




> *Brent Zundel:* [https://github.com/w3c/did-wg-charter/issues](https://github.com/w3c/did-wg-charter/issues)

**Brent Zundel:** the reason this is a longer topic is due to issues that have been raised that we should discuss  
… the goal is to go through them briefly, then I encourage WG members to respond in the issues  
… the first issue is "one foundational key representation please" from Microsoft.  
… this has received extensive discussion in the WG already  

**Drummond Reed:** folks are still encouraged to reply in the issue, especially with citations to our earlier discussions of those topics.  

**Brent Zundel:** Microsoft is recommending non-normative guidance on cross-compatibility between JSON and JSON-LD  
… this sort of non-normative guidance would, in Brent's opinion, be in scope under the new charter  
… but would also retrod well-trodden ground  
… Microsoft would also like the WG to take the challenge to define a universal, mandatory-to-implement DID method  
… this would take the WG out of maintenance mode  

**Joe Andrieu:** There was a proposal to include `did:web` and `did:key` in the charter, but that was not done in order to keep it a maintenance WG  
… so this could be a chance to do that  

**Kyle Den Hartog:** `did:key` could work, but worried that `did:web` would derail the conversation  
… and not sure what would be the third  

**Brent Zundel:** The question of what DID methods could reach consensus would be challenging  
… `did:peer` might also be a candidate that could reach consensus  

**Ted Thibodeau Jr.:** Going through the exercise of determining which DID methods could become normative could be a work item for the W3C Credentials Community Group  
… but the DID Rubric might be a better tool for evaluating this  

**Drummond Reed:** likes the idea of looking at the DID Rubric and taking an evolutionary path  

</details>

**Comment by brentzundel** [comment]
Beginning standardization of DID Methods was added to the charter in #20
