### ISSUE TITLE
Standardize three "truly decentralized" DID Methods

### ISSUE THREAD

**Issue by msporny** [w3c/did-wg-charter#14]
This issue has been raised for discussion by the DID WG based on feedback in Google's Formal Objection to DID Core 1.0 (this is neither my or my organization's position -- I'm just the messenger):

https://lists.w3.org/Archives/Public/public-did-wg/2021Oct/0022.html

Google and Mozilla would like us to standardize three "truly decentralized" DID Methods to demonstrate practical interoperability. Google has asserted that `did:web` and `did:key` are not decentralized enough. The chartering question is then, if not those two methods, then what DID Method is capable of meeting the combination of requirements that Apple, Google, and Mozilla proposed, which are:

1. Must be "truly decentralized". Certificate Transparency was suggested as in the realm of possibility.
2. Must not be environmentally unsustainable, where proof-of-work consensus is regarded as environmentally unsustainable.
3. Must not be `did:key` or `did:web`, and presumably any DID Method that has qualities similar to those DID Methods as Google listed those as "not decentralized enough".
4. Must meet all criteria listed in [DID Core: Method Requirements](https://www.w3.org/TR/did-core/#methods)
5. Must contain a sustainability cost/benefit analysis in the DID Method specification.
6. Must specify (either directly or by reference to an external specification with the same level of expert review and process consensus) the consensus and gossip algorithm and demonstrate independent implementations of network software using a W3C test suite.

Should a future DID WG Charter standardize "more decentralized" methods? If so, which DID Methods would meet the requirements above?

**Comment by rxgrant** [comment]
> @rxgrant waved in this direction by talking about "more respected DID Methods". That's the group that Google's formal objection suggested standardizing. The market would remain free to pick non-standardized methods if their benefits along other axes outweighed their centralization along the standardization axis.

I'd like to see as informed a marketplace as possible, for the ease of implementors deciding what to implement and end users picking trustworthy tools.  Some user choices of DID Method are going to seem unnecessary when looking in from the outside, but will have at their heart intricate reasons like tool experimentation or custody features.

We've done a lot of work to define criteria in the Rubric that will resonate with different people.  One of those criteria (whether it's listed yet or not) will be widespead support (with support helped along by its cousin: widespread use of trusted models like external resolvers).  One of the consequences of not picking winners in the spec is that clarity may take time.

I think the decentralization needs of the users outweigh the clarity needs of implementors, in this case.

**Comment by jyasskin** [comment]
Standardization can also help with patent claims, which seem to be missing from the Rubric (https://github.com/w3c/did-rubric/issues/65).

**Comment by peacekeeper** [comment]
`did:web` is always a great example. This method is based on domain names, which in the classic sense and by most definitions is not "decentralized" (see https://en.wikipedia.org/wiki/Zooko's_triangle). One of the main reasons why work on DIDs started was that identifiers were needed that are NOT dependent on central authorities like domain names are.

BUT: `did:web` shares its syntax, data model, and resolution interface with all other compliant DID methods, and that's why people in this community often prefer to use `did:web` over `https://` nowadays.

As others have said, this makes it possible to build applications and services that work with many different types of identifiers, and to easily switch out identifier and resolution systems. It has been argued that this aspect by itself is also a form of decentralization.

**Comment by brentzundel** [comment]
Beginning standardization of DID Methods was added to the charter in #20
