### ISSUE TITLE
Standardize did:key

### ISSUE THREAD

**Issue by msporny** [w3c/did-wg-charter#15]
This issue has been raised for discussion by the DID WG based on feedback in Google's Formal Objection to DID Core 1.0:

https://lists.w3.org/Archives/Public/public-did-wg/2021Oct/0022.html

Google has suggested that while `did:key` does not meet their "truly decentralized" requirement for a DID Method, that they suggest that the DID WG standardizes it.

Should a future DID WG Charter standardize `did:key`?

**Comment by jyasskin** [comment]
A nit: `did:key` is decentralized. Its utility problem is rather that it can't deal with key loss or compromise, since the identity is identical with the public key. It's not sufficient for demonstrating that the `did:` scheme's abstractness is needed, since it doesn't implement all 4 "virtual methods", but as Manu said, it's still worth standardizing.

**Comment by brentzundel** [comment]
Beginning standardization of DID Methods was added to the charter in #20 
One of these may be `did:key`
