### ISSUE TITLE
Do not standardize DID Methods that are not environmentally sustainable

### ISSUE THREAD

**Issue by msporny** [w3c/did-wg-charter#17]
This issue has been raised for discussion by the DID WG based on feedback in Mozilla's Formal Objection to DID Core 1.0 (this is neither my or my organization's position -- I'm just the messenger):

https://lists.w3.org/Archives/Public/public-new-work/2021Sep/0000.html

Mozilla stated:
> We must instead firmly oppose such proof-of-work technologies including to the best of our ability blocking them from being incorporated or enabled (even optionally) by any specifications we develop.

Per Mozilla's suggestion, should a future DID WG Charter that standardizes DID Methods contain language the specifically places proof-of-work DID Methods as "out of scope"?

**Comment by csuwildcat** [comment]
I was on a recent W3C call on the topic of sustainability, and the people on the call were pushing misinformation and dubious news headlines. They didn't even realize electricity ≠ emissions, had no idea PoW systems primarily tap waste energy from green/renewable sources that would otherwise go unused, and lacked basic economic/infrastructure knowledge about energy systems. When confronted with data-reality, they simply refused to acknowledge it and repeated conclusively debunked claims. I can't tell exactly which it is, but the folks leading this anti-PoW charge are either innocently or willfully uneducated on this topic. The anti-PoW opposition I have heard thus far has lacked academic rigor to a degree that is seriously concerning, and folks who are either too busy or unwilling to invest the time to become educated about a topic should have 0 say over it.

It is my personal opinion that this Issue should be closed with extreme prejudice.

**Comment by jandrieu** [comment]
> Hopefully, this illuminates what I meant by "market failure" as well as some of things that make it hard to accept without some skepticism even earnestly asserted claims that Bitcoin mining is an unalloyed benefit to the electric grid. As is the case with many such issues, the reality is a bit more complex than advocates proclaim.

Excellent. I believe we are in complete agreement here. I don't believe anyone suggested that "bitcoin mining is an unalloyed benefit". That would be an untenable assertion. My point is the same as yours: reality is more complex than advocates of this issue have acknowledged. You can't simply estimate a ballpark of the total electicity usage of bitcoin and blindly claiming that PoW is unsustainable. Well, you **can**, it just wouldn't be scientifically valid.

**Comment by jandrieu** [comment]
> Nonetheless, my personal opinion is that any DID method which satisfies the rubric, and is likely to be used, should be registered.

Please note that "satisfying the rubric" is not a thing.

Even the crappiest method can be evaluated. Evaluations don't result in a canonical yes or no, valid or invalid, satisfied or unsatisfied.

People use the rubric to select the criteria they care about to evaluate the methods they care about. The result is a bespoke evaluation from a subset of criteria representing one evaluators judgment for those criteria. When aggregated across methods, it provides a way to compare DID Methods on an apples-to-apples basis using the criteria that matter most to the party doing that aggregation.

It is fundamentally a subjective process that represents the judgment of a particular person or team at a particular point in time for particular use cases. It does NOT result in an objective anything. Any attempt to do so would undermine the very decentrality we are here supporting. What matters to one person may or may not matter to another. What matters in one use case may not matter in another. The Rubric does not stand in as an arbiter of what makes a "good" method.

**Comment by bobwyman** [comment]
@jandrieu writes:

- "Proof of Stake and other non-PoW approaches do not achieve the same ends."
- "there is no known solution [to actual decentralization against bureaucratic overreach] that, in fact, represents an 'alternative means to the same ends'."
- "PoW ... is foundational to the entire DID gestalt."
- "To propose that PoS is an equivalent [to PoW] is the kind of misunderstanding or ignorance that others have called out."

While repetition is a useful indicator of the author's strength of conviction, such repetition does little to illuminate the reasons why PoS, or any other alternative to PoW, would not "achieve the same ends" as PoW.

The fact that alternatives to PoW have been and are being proposed indicates that a belief in the absolute superiority of PoW is somewhat controversial. It also appears that some systems that began using PoW, such as Ethereum, are now in the process of converting to PoS.

Given that controversy exists, I would appreciate it very much if someone could identify at least the essential attributes of PoS, or other alternatives, that cause it to appear so deficient to the advocates of PoW.

bob wyman

**Comment by rxgrant** [comment]
> I would appreciate it very much if someone could identify at least the essential attributes of PoS, or other alternatives, that cause it to appear so deficient to the advocates of PoW.

The very short answer is that it costs energy to build the castle to protect staked coins from all possible attacks, and if the cost of the attack is less than the payoff, it's rational to put further resources into protecting the stake.  The original declaration of this principle was outlined in [Nothing is Cheaper than Proof of Work](https://www.truthcoin.info/blog/pow-cheapest/), an essay from 2015 by Paul Sztorc.

Similar security problems affect any organization with large holdings, even under the proof-of-work cryptocurrencies, but any successful attack there would not be a systemic risk to the rest of the blockchain's operation (although hashrate does drop for a while when the market reacts to disasters).

Fungibility in effort was empirically observable during the launch of Chia earlier this year, an "[eco-friendly](https://www.chia.net/faq/#faq-10)" [proof-of-space](https://en.wikipedia.org/wiki/Proof_of_space) cryptocurrency, which ended up consuming hard drive stock and manufacturing capacity, [causing a hard drive shortage](https://www.tomshardware.com/news/chia-mining-craze-easing-but-hdd-pricing-still-rising).

*P.S.* Off-topic but of interest to the thread in general: Sztorc wrote [an essay](https://www.truthcoin.info/blog/security-budget-ii-mm/) earlier this month on why hashrate (and thus energy usage) will fall as the subsidy halves again and again, if no other mechanism to pay for security is developed.

**Comment by rxgrant** [comment]
> [...] essential attributes of PoS, or other alternatives, that cause it to appear so deficient to the advocates of PoW.

Oh, the other reason is that Bitcoin's proof-of-work distribution function was the only fair way to do it that was available on day one, and they're sticking to it.  

This fairness issue is more relevant to money than reliable DID updates.   However, people want to express their values on these matters, so they don't want to ignore distribution fairness any more than they want to ignore effects on the environment.

If you, the founder, are starting a proof-of-stake blockchain, you have to ask how you're distributing the coins...  

Do you just sell them?  But you must keep some for your development team, which you control, or no one will believe the coins will maintain any value...  To this day Ethereum issued more coins in its ICO than have ever been mined, if I recall correctly.  Cardano [laundered its ICO through Japan](https://dailyhodl.com/2021/07/09/legal-expert-weighs-likelihood-that-cardano-dogecoin-polkadot-and-uniswap-will-face-regulatory-action-from-the-sec/).
  
Did a cryptocurrency start with proof-of-work but now professes to be moving off?  The miners will work to delay that (as they have for Ethereum, going on seven years now).

Do you skip coins and pick some companies to be functionaries?  Several VDRs in this space were created by companies that have partnered up with similarly interested companies in order to be decentralized.  This federation model is very close to proof-of-stake (validate updates with signatures, sometimes in exchange for an operator reward), and I have no problem with it.  But none of them have achieved more than a few dozen node operators enforcing their DID Method rules, which means that they're subject to only a few local jurisdictions (and sometimes that's stable enough, but it's a different threat model).   So if a DID Method design team wants their method to be completely decentralized, then the best available design space is highly incentivized global blockchains.

Even if our hypothetical founder does, somehow, initially distribute proof-of-stake coins fairly, staking has structural inequality.  The more coins one has, the more staking rewards one gets. Capital helps miners in proof-of-work, too, but if you look at the volatile history of top miners, and especially the [steep price that BitMain paid](https://blockonomi.com/fall-of-bitmain/) for its mistakes in the [blocksize war](https://www.amazon.com/Blocksize-War-controls-Bitcoins-protocol/dp/B08YQMC2WM), you can see that there's a lot more to it.

Proof-of-work in Bitcoin levels the playing field.  Even leveling the playing field doesn't directly address prior unjust inequality, but it does reward curiosity, innovation, and hard work over long periods of time.

*P.S.*  The original paper on why proof-of-stake doesn't work is [On Stake and Consensus](https://download.wpsoftware.net/bitcoin/pos.pdf), by Andrew Polestra, last revised in 2015.  The main point is that there is no external source of truth corroborating the checkpoints that you first see.  The argument is hard to apply to recent proof-of-stake proposals because they have become so complicated, so I started out with shorter answers.

**Comment by OR13** [comment]
Glad to see the issue is progressing.

> Even the crappiest method can be evaluated [ / registered ]. 

I think this is the key topic for us to discuss regarding registries at W3C.

Specifically, there are registries with values baked in, and ones which strive not to have values baked in.

On a side note, calling methods "crappy or dog****" is a way of trying to inject values into a registry, and I think its a terrible idea.... there are lots of registries with various quality and quantity of entry.... and complaining about the quality of items in a list eventually extends to complaining about the list itself. Have a look at this registry:

https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml

Are we going to say there are a lot of "crappy or dog****" cbor tags? we should discourage the use of such language, I don't think the folks using it intend to cause harm, but there is real potential for it if we continue to use this kind of tone.

The rubric has at least some values baked in.

One of those values is that "any method can be evaluated"... 

The other part of @jandrieu's answer is also correct imo:

> Evaluations don't result in a canonical yes or no, valid or invalid, satisfied or unsatisfied.

I think folks often seek this kind of thing without realizing how hard it is to get in a fair way for everyone, and how likely we are to end up in a situation that is unfair and filled with bias....

Let's consider DID Core v1 Conformance a rubric criteria, and ask: 

Should did methods that have a privacy and security considerations section that is __almost__ empty evaluated?

IMO, the answer is yes... however, the confidence of everyone in any evaluation for such a method is low... after all, there was not a lot to evaluate.

Now let's imagine 5 years from now, W3C has a new mandatory section called "Environmental, Ethical and Social" considerations.... DID Core could require method specs to have such a section. 

Some methods might put a lot of time and effort into that section.... they might invent fantastic atomic swap / proof of stake / carbon credit awesomeness. 

Others might say electricity is required by most processing systems, and electricity should be derived from renewable sources whenever possible.

When performing a rubric evaluation, these sections of the method spec can be relied on.... but I don't think the rubric, or the did core v1 spec is the right place to tell a did method author what they are or are not allowed to use to build a did method, nor is either the right place to tell them if they "considered the environment enough"... its not possible to achieve that.... we can always do better.

In summary, DID WG members (and W3C generally) should avoid taking the position that we can alter culture through normative statements in specs. 

We can say things like: address these 5 questions... but the second we start grading answers from different political perspectives as "passing or failing" we are in deep trouble... privacy, sustainability, security.... all of these are political issues today.... we don't want to encourage folks to play games with addressing them, by punishing or privileging attempts to speak to values that overlap with our own... we want to encourage authors to address them to the best of their ability...

If a method author thinks carbon credits and proof of stake are a better solution than proof of work and wind energy, let them spend their time arguing for that in their method... The current normative requirements for did methods do not require them to do that, but they remain free to exceed those requirements if they are passionate enough.

The rubric is meant to give folks questions and tools to evaluate did methods... we are not here to make the bar easier or harder to meet for specific technologies, or bias the bars towards certain evaluation outcomes.

The did spec registries is meant to be a list of pointers to specs, not a place to pick winners, or pseudo-evaluate did methods.

The did core v1 spec has normative requirements for a conforming did method spec, those requirements don't enable us to evaluate if a required section was "bad", "ok" or "excellent"... and probably experts won't agree on some sections (such as privacy or security benefits of public ledger systems)...

**Comment by bobwyman** [comment]
@jandrieu wrote:
> Please note that "satisfying the rubric" is not a thing.

Please forgive my imprecise writing. By "satisfy the rubric" I meant only that the rubric had been responded to; that the DID method authors had made an apparently good faith effort to consider and respond to the rubric. I do not suggest that any metric for a "correct" or even "satisfactory" response should be imposed.

I believe that the registry should be nothing more than a mere public listing that identifies, and provides access to descriptions of, DID methods associated with DIDs that my code may come across. The mere fact that a DID method is registered should not imply that it has been standardized, endorsed, or even evaluated by the W3C or any of its working groups, community groups, or whatever. (i.e. If a Bitcoin-specific DID method is "standardized," it should be standardized by whatever community defines Bitcoin standards, but, whatever the Bitcoin folk come up with, and no matter how much others may object to or support what they do, if others are likely to be exposed to their DIDs, then their DID method should be registered.)

Some DID methods may be deficient in meeting requirements, such as those for security or privacy, that are widely accepted by the community. Some DID methods might rely on truly bizarre or onerous technical requirements. But none of that should influence what is or is not registered. If a DID method is in use, and I discover a DID which uses a DID method with which my code is unfamiliar, I should have a means to discover the intended methods associated with that DID. Of course, on inspecting the DID method's definition and rubric answers, I might decide that I have no intention of supporting such DIDs. On the other hand, I might decide to invest in whatever development is needed to support them. However, without a registry, I have no opportunity to make these decisions. I should have the freedom to choose.

While I don't think that the W3C should be involved in the "standardization" of DID methods, I do think it would make sense for the W3C to non-exclusively highlight one or a very small number of DID methods that do, in fact, satisfy some broadly accepted set of requirements and that can be implemented with a minimum number of technical dependencies. Thus, I would support the W3C's non-exclusive highlighting of DID methods such as the now registered did:web method, or [the did:tag method](https://github.com/w3c-ccg/community/issues/216) that I have proposed, but not registered. The non-exclusive endorsement of such easily implemented and broadly useful DID methods should be intended only to highlight suggested "defaults" for those who need DIDs but who don't have any requirements that would cause them to need to rely on some other DID method or to go to the trouble of defining their own unique DID methods.

bob wyman

**Comment by brentzundel** [comment]
Beginning standardization of DID Methods was added to the charter in #20 
Which methods to choose, if any, will be determined by the WG.
