### ISSUE TITLE
Consider chartering DID Resolver WG first

### ISSUE THREAD

**Issue by ChristopherA** [w3c/did-wg-charter#28]
As per @TallTed in https://github.com/w3c/did-wg-charter/pull/27#issuecomment-1382091353 and  @jandrieu in https://github.com/w3c/did-wg-charter/pull/27#issuecomment-1370900227 and #24

Shouldn't we reconsider chartering this working group and instead focus on chartering a DID Resolver WG?

**Comment by brentzundel** [comment]
I welcome seeing a draft charter. I'd be happy to review it.

**Comment by jandrieu** [comment]
@brentzundel As I mentioned in Miami, I'm helping @ChristopherA to put something together.

**Comment by peacekeeper** [comment]
Also happy to review it..

**Comment by talltree** [comment]
As am I.

**Comment by brentzundel** [comment]
Has development of a DID Resolution charter progressed to the point where it would be best to remove mention of DID Resolution from this charter?

**Comment by jandrieu** [comment]
I haven't heard any objections to including DID Resolution in this charter, so I would question why it would be removed.

If this charter is the one to be put forward by the group, IMO, it should include resolution.

**Comment by brentzundel** [comment]
I ask because it does not make sense to charter a DID WG that includes DID Resolution at the same time as chartering a DID Resolver WG. It seemed that the intention was to write a charter for DID Resolver WG.

**Comment by jandrieu** [comment]
> I ask because it does not make sense to charter a DID WG that includes DID Resolution at the same time as chartering a DID Resolver WG.

Agreed.

Both Christopher Allen and I suggested on #27 that we focus the DID WG Charter on Resolution, in part because that appeared to be the overwhelming consensus of the group at TPAC, while standardizing DID Methods did not have consensus. I suggested we change the name of the charter to DID Resolution WG Charter to overcome the political position that a DID WG is somehow required by W3C leadership to develop DID Methods.

@TallTed replied to Christopher's suggestion with an ask that we create a separate issue to discuss a different charter instead.

So Chris created this issue and we are working on an alternative charter. We've done this, in part, because we believe the inevitable political process will be best served by having explored all available options before escalating to Formal Objections.

The soon-to-be-proposed DID Resolution WG Charter is an alternative to the DID WG Charter for WG consideration. If the WG should choose to publish a non-consensus charter that focuses on a DID WG with scope to develop individual DID methods, then those of us who think that's a horrible idea will of course consider placing a separate DID Resolution WG Charter before the W3C on our own. At this point, however, the conversation is about the charter proposal to be put forth by the current DID WG.

To date, there have been no objections, technical or otherwise, to Resolution in the DID WG Charter and hence, no basis at all for removing it.

In fact, resolution appears to be the only substantive new deliverable that does have consensus.

**Comment by peacekeeper** [comment]
As discussed before, whether or not to include DID methods is a difficult question.

I share the concerns about "picking winners", and I'm very happy that Joe and Christopher are working on an alternative charter proposal, so we can compare it with https://github.com/w3c/did-wg-charter/pull/27.

**Comment by ChristopherA** [comment]
On Mar 10, 2023 at 9:58:47 AM, Markus Sabadello ***@***.***>
wrote:

> As discussed before, whether or not to include DID methods is a difficult
> question.
>
> I share the concerns about "picking winners", and I'm very happy that Joe
> and Christopher are working on an alternative charter proposal, so we can
> compare it with #27 <https://github.com/w3c/did-wg-charter/pull/27>.
>

The alternative proposal (to replace the current draft of a DID-WG charter
with a DID-Resolution-WG charter) is now available at:

https://github.com/w3c/did-wg-charter/pull/30

— Christopher Allen

**Comment by jandrieu** [comment]
I want to thank @burnburn for recommending in email that the AC meeting is the "right" place to have this conversation. I found that assertion problematic in September when 4 out of 5 people I know who oppose the inclusion of DID methods are invited experts who aren't allowed to participate in AC meetings, including myself. (My company joined the W3C to engage on this issue.)

But Dan had a point.

I just wrapped up two days at the annual W3C AC meeting and it was absolutely the right place to discuss these issues. I was able to speak not only with staff but with the AC reps of all three prior objectors (Google, Apple, and Mozilla). I don't want to speak on their behalf in particular, but there was exceptional support for focusing on resolution rather than DID methods as the route to interoperability. "That would go a long way to addressing our concerns" and "Yep, that seems like the better way to do it" and "That seems reasonable, but I need to think on it a bit more [before I say it resolves the issues of our FO]."

I think it's fair to say that a focus on resolution (without any DID methods) would likely avoid a FO from 2 out of 3 and, quite possibly all 3.

I also had a good, albeit brief, discussion about the sustainability question at the heart of the Mozilla objection, which still needs some work for us to address. That's not related to this Github issue, so I'll leave that discussion for another thread.

I think this is promising progress on how we address the real issues behind the prior FOs as we prepare for rechartering.

My sense after the AC meeting is that what will best serve the work is not a DID Resolution WG but rather a DID WG whose deliverables are focused on resolution. I think Christopher's PR #30 has a reasonable first pass at refocusing a charter for Resolution, but 
1. It hasn't had the chance to mature. It could use feedback and engagement.
2. It currently is written as the DID Resolution WG Charter, which no longer seems like the right way forward.

The most salient difference is putting Resolution in the foreground as a normative, standards track document. Perhaps we can use that language as a starting point for a revised DID WG charter.

The W3C team is still working through my appeal and there remain nuances to address. I can't say how that conversation will resolve, but I think we now can at least see a path forward with the potential to avoid Formal Objections altogether (at least on the issue of specifying DID Methods).

**Comment by brentzundel** [comment]
@jandrieu thank yo for having those conversations. I am very grateful you were able to attend the AC meeting and that it was fruitful. I am also confident that we can successfully move through the charter development process and end up with something that no one objects to (possibly even something that most people like). I appreciate your commitment to this work.

**Comment by plehegar** [comment]
Closing this issue here since we started the AC review. There is a comment related to this issue at
 https://github.com/w3c/charter-drafts/issues/427 so please follow up there if needed.
